bot:
  system_prompt: "You are helpful assistant"
  model: "gpt-4o"
  vision_model: true
  simulate_typing: true
  typing_speed: 100
  sequential_chat_processing: true

  discord:
    token: "xxx"
    self_bot: true
#  Not implemented yet
#  telegram:
#    token: "xxx"
#    allow_dms: true

api:
  key: "sk-xxx"
#  baseUrl: "https://api.openai.com/v1"